environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python36-x64"

#- PYTHON: "C:\\Python27"
#    - PYTHON: "C:\\Python35"
#    - PYTHON: "C:\\Python27-x64"
#    - PYTHON: "C:\\Python35-x64"

install:
- git submodule update --init --recursive
- cd flame-blis
  #- set "CONDA_INSTALL_LOCN=C:\\Miniconda36-x64"
  #- call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  #- conda update --yes --quiet conda
  #- conda config --add channels conda-forge
  #- conda install --yes clangdev posix m2-make pthreads-win32
- choco install make
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
- set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
- set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%"
#- cd ..


build_script:
- set CC=clang
- set RANLIB=echo
- set AR=llvm-ar
- set AS=llvm-as
- set LIBPTHREAD=-lpthreads
- cd %APPVEYOR_BUILD_FOLDER%
- cd flame-blis
- dir .
- bash -lc "ln -s $APPVEYOR_BUILD_FOLDER /c/projects/cython-blis"
- dir C:\projects
- bash -lc "cp /c/projects/cython-blis/extra-include/configure /c/projects/cython-blis/flame-blis"
- bash -lc "cd /c/projects/cython-blis/flame-blis && ./configure --disable-static --disable-shared --disable-threading --enable-verbose-make --enable-arg-max-hack haswell"
- bash -lc "cp /c/projects/cython-blis/extra-include/*.h /c/projects/cython-blis/flame-blis/include/haswell"
- bash -lc "cd /c/projects/cython-blis/flame-blis && make AR=llvm-ar CPICFLAGS= LIBM= | python ../bin/munge_make_log.py > ../blis/_src/make/msvc.jsonl"
- bash -lc "cp /c/projects/cython-blis/blis/_src/make/msvc.jsonl $APPVEYOR_BUILD_FOLDER/blis/_src/make"
  #- bash -lc "source activate && cd /c/projects/cython-blis/ && cp flame-blis/include/x86_64/blis.h blis/_src/include/blis.h"
  #- cd C:\projects\cython-blis
  #- "%PYTHON%\\python.exe -m pip install -U pip"
  #- "%PYTHON%\\python.exe -m pip install wheel"
  #- "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"
  #- "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  #- "%PYTHON%\\python.exe setup.py bdist_wheel"
  #- "%PYTHON%\\python.exe -m pip install dist/*.whl"


test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  #- "%PYTHON%\\python.exe -m pytest tests/"

artifacts:
  - path: blis/_src/make
    name: msvc.jsonl
