environment:

  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
- set "PATH=%PYTHON%;%path%"

build_script:
- python -m pip install -U pip wheel
- python -m pip install -r dev-requirements.txt"
- python -m pip install -r requirements.txt
- python setup.py bdist_wheel

test_script:
- cd C:\
- python -m venv .env
- bash -lc "cp -r $APPVEYOR_BUILD_FOLDER /c/build"
- bash -lc "/c/.env/Scripts/python -m pip install /c/build/dist/*.whl"
- C:\.env\Scripts\activate
- python -m pip install pytest hypothesis
- python -m pytest %APPVEYOR_BUILD_FOLDER%\tests

artifacts:
  - path: dist/
    name: wheels
