environment:

  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
- set "PATH=%PYTHON%;%path%"

build_script:
- python -m pip install -U pip wheel
- python -m pip install -r requirements.txt
- python setup.py bdist_wheel
- cd ..
- python -m pip install %APPVEYOR_BUILD_FOLDER%\dist\*.whl

test_script:
- python -m pytest --pyargs blis

artifacts:
  - path: dist/
    name: wheels
