environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.
    - PYTHON: "C:\\Python36-x64"

#- PYTHON: "C:\\Python27"
#    - PYTHON: "C:\\Python35"
#    - PYTHON: "C:\\Python27-x64"
#    - PYTHON: "C:\\Python35-x64"

install:
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
#- git submodule update --init --recursive
#- set "CONDA_INSTALL_LOCN=C:\\Miniconda36-x64"
#- call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
#- conda update --yes --quiet conda
#- conda config --add channels conda-forge
#- conda install --yes clangdev posix m2-make
#- set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
#- set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%"


build_script:
- set CC=clang
- set RANLIB=echo
- set AR=llvm-ar
- set AS=llvm-as
- bash -lc "ln -s $APPVEYOR_BUILD_FOLDER /c/projects/cython-blis"
- bash -lc "which clang"
- cd %APPVEYOR_BUILD_FOLDER%
- bash -lc "cd /c/projects/cython-blis && python3 -m pip install -U pip"
- bash -lc "cd /c/projects/cython-blis && python3 -m pip install wheel"
- bash -lc "cd /c/projects/cython-blis && python3 -m pip install -r dev-requirements.txt"
- bash -lc "cd /c/projects/cython-blis && python3 -m pip install -r requirements.txt"
- bash -lc "cd /c/projects/cython-blis && python3 setup.py bdist_wheel"
- bash -lc "cd /c/projects/cython-blis && python3 pip install dist/*.whl"
- bash -lc "mkdir -p $APPVEYOR_BUILD_FOLDER/dist/"
- bash -lc "source activate && cp /c/projects/cython-blis/dist/*.whl $APPVEYOR_BUILD_FOLDER/dist/"

#test_script:
# Put your test command here.
# If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
# you can remove "build.cmd" from the front of the command, as it's
# only needed to support those cases.
# Note that you must use the environment variable %PYTHON% to refer to
# the interpreter you're using - Appveyor does not do anything special
# to put the Python version you want to use on PATH.
#- bash -lc "source activate && cd /tmp && python -m pytest /c/projects/cython-blis/tests"

artifacts:
  - path: blis/_src/make
    name: make_scripts.jsonl
  - path: blis/dist
    name: wheels
