environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python36-x64"

#- PYTHON: "C:\\Python27"
#    - PYTHON: "C:\\Python35"
#    - PYTHON: "C:\\Python27-x64"
#    - PYTHON: "C:\\Python35-x64"

install:
- git submodule update --init --recursive
- cd flame-blis
- set "CONDA_INSTALL_LOCN=C:\\Miniconda36-x64"
- call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
- conda update --yes --quiet conda
- conda config --add channels conda-forge
- conda install --yes clangdev posix m2-make pthreads-win32
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
- set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
- set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%"


build_script:
- set CC=clang
- set RANLIB=echo
- set AR=llvm-ar
- set AS=llvm-as
- cd %APPVEYOR_BUILD_FOLDER%
- cd flame-blis
- bash -lc "ln -s $APPVEYOR_BUILD_FOLDER /c/projects/cython-blis"
- bash -lc "which clang"
- bash -lc "source activate && cd /c/projects/cython-blis && python -m pip install -U pip"
- bash -lc "source activate && cd /c/projects/cython-blis && python -m pip install wheel"
- bash -lc "source activate && cd /c/projects/cython-blis && python -m pip install -r dev-requrements.txt"
- bash -lc "source activate && cd /c/projects/cython-blis && python -m pip install -r requirements.txt"
- bash -lc "source activate && cd /c/projects/cython-blis && python setup.py bdist_wheel"
- bash -lc "source activate && cd /c/projects/cython-blis && python pip install dist/*.whl"
- bash -lc "mkdir -p $APPVEYOR_BUILD_FOLDER/dist/"
- bash -lc "cp /c/projects/cython-blis/dist/*.whl $APPVEYOR_BUILD_FOLDER/dist/"

#test_script:
# Put your test command here.
# If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
# you can remove "build.cmd" from the front of the command, as it's
# only needed to support those cases.
# Note that you must use the environment variable %PYTHON% to refer to
# the interpreter you're using - Appveyor does not do anything special
# to put the Python version you want to use on PATH.
#- bash -lc "source activate && cd /tmp && python -m pytest /c/projects/cython-blis/tests"

artifacts:
  - path: blis/_src/make
    name: make_scripts.jsonl
  - path: blis/dist
    name: wheels

#- bash -lc "source activate && cd /c/projects/cython-blis/flame-blis && ./configure --disable-shared --disable-cblas --disable-blas --disable-threading --enable-verbose-make --enable-arg-max-hack --prefix=/c/blis x86_64"
#- bash -lc "source activate && cd /c/projects/cython-blis/flame-blis && make AR=llvm-ar CPICFLAGS= LIBM= -j4 > make.log"
#- bash -lc "source activate && cd /c/projects/cython-blis && cat flame-blis/make.log | python bin/munge_make_log.py > blis/_src/make/msvc.jsonl"
#- bash -lc "mkdir -p /c/projects/cython-blis/blis/_src/include/windows-x86_64"
#- bash -lc "cp /c/projects/cython-blis/flame-blis/bli_config.h /c/projects/cython-blis/blis/_src/include/windows-x86_64"
#- bash -lc "cp /c/projects/cython-blis/flame-blis/include/x86_64/blis.h /c/projects/cython-blis/blis/_src/include/windows-x86_64/blis.h"
#- bash -lc "cp /c/projects/cython-blis/flame-blis/include/x86_64/blis.h /c/projects/cython-blis/blis/_src/include/x86_64/blis.h"
#- bash -lc "cp /c/projects/cython-blis/flame-blis/bli_config.h /c/projects/cython-blis/blis/_src/include/windows-x86_64/bli_config.h"
#- bash -lc "cp /c/projects/cython-blis/flame-blis/bli_config.h /c/projects/cython-blis/blis/_src/include/x86_64/bli_config.h"
#- bash -lc "cp /c/projects/cython-blis/blis/_src/make/msvc.jsonl $APPVEYOR_BUILD_FOLDER/blis/_src/make/msvc.jsonl"
#- bash -lc "cp /c/projects/cython-blis/blis/_src/include/windows-x86_64/*.h $APPVEYOR_BUILD_FOLDER/blis/_src/make/"


