language: python
sudo: required
dist: xenial

matrix:
  include:
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION="3.5"
  - os: linux
    python: "3.5"
  - os: linux
    python: "3.6"
  - os: linux
    python: "3.7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; source ./travis/before_install_osx.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; source ./travis/before_install_linux.sh
  - before_install

install:
        # TODO: Use homebrew to install pyenv, set Python version
  - python -m pip install -r requirements.txt
  - python setup.py bdist_wheel
  - rm -rf blis*
  - python -m pip install dist/*.whl

script:
  - python -m pytest tests/

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - clang

notifications:
  email: false
  slack:
    secure: VSqtxg7u4NTZRfoZqjxPRPVS92KTy/mp62egfDZ9ujTP4VPxNe15QZuTB6r/ICPgEYqBtdhLc/aetuBcemt0bHfentV0F7bz7iDY/AFQC1h1i4G0D0wKMufuqOJFw9MOp2tSpuvCVzhCxR+Ymx/F9SaeYBAiwBawce4wu+qu3lA=
