language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.5"
  - "3.6"

os:
  - linux
  - osx


install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo rm -f /usr/bin/as; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -s /usr/lib/binutils-2.26/bin/as /usr/bin/as; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo rm -f /usr/bin/ld; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -s /usr/lib/binutils-2.26/bin/ld /usr/bin/ld; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sed -i 's/"gcc"/"gcc-6"/' blis/_src/make/gcc.jsonl ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CC="gcc-6"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./bin/generate-make-jsonl clang; fi
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - pip install dist/*.whl

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - binutils-2.26
    - clang


script:
  - cp -r tests/ /tmp/blis-tests
  - cd /tmp
  - python -m pytest blis-tests/

after_success:
  coveralls

notifications:
  email: false
  slack:
    secure: VSqtxg7u4NTZRfoZqjxPRPVS92KTy/mp62egfDZ9ujTP4VPxNe15QZuTB6r/ICPgEYqBtdhLc/aetuBcemt0bHfentV0F7bz7iDY/AFQC1h1i4G0D0wKMufuqOJFw9MOp2tSpuvCVzhCxR+Ymx/F9SaeYBAiwBawce4wu+qu3lA=
