language: python
sudo: required
dist: xenial
osx_image: xcode10

matrix:
  include:
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION="3.5"
  - os: linux
    language: generic
    env:
    - MB_PYTHON_VERSION="3.5"


install:
  - source ./bin/travis_setup.sh
  - python -m pip install -r requirements.txt
  - python setup.py bdist_wheel
  - python -m pip install dist/*.whl

script:
  - python -m pytest tests/

after_success:
  coveralls

notifications:
  email: false
  slack:
    secure: VSqtxg7u4NTZRfoZqjxPRPVS92KTy/mp62egfDZ9ujTP4VPxNe15QZuTB6r/ICPgEYqBtdhLc/aetuBcemt0bHfentV0F7bz7iDY/AFQC1h1i4G0D0wKMufuqOJFw9MOp2tSpuvCVzhCxR+Ymx/F9SaeYBAiwBawce4wu+qu3lA=
