language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - cd flame-blis
  - ./configure --disable-threading --enable-verbose-make x86_64
  - make | python ../bin/munge_make_log.py > ../blis/_src/make/gcc.jsonl
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - pip install dist/*.whl

script:
  - cd /tmp
  - python -m pytest --pyargs blis --cov=blis

after_success:
  coveralls

notifications:
  email: false
  slack:
    secure: VSqtxg7u4NTZRfoZqjxPRPVS92KTy/mp62egfDZ9ujTP4VPxNe15QZuTB6r/ICPgEYqBtdhLc/aetuBcemt0bHfentV0F7bz7iDY/AFQC1h1i4G0D0wKMufuqOJFw9MOp2tSpuvCVzhCxR+Ymx/F9SaeYBAiwBawce4wu+qu3lA=
