language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.5"
  - "3.6"

os:
  - linux

install:
  - source ./bin/travis_setup.sh
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - pip install dist/*.whl

script:
  - cp -r tests/ /tmp/blis-tests
  - cd /tmp
  - python -m pytest blis-tests/

after_success:
  coveralls

notifications:
  email: false
  slack:
    secure: VSqtxg7u4NTZRfoZqjxPRPVS92KTy/mp62egfDZ9ujTP4VPxNe15QZuTB6r/ICPgEYqBtdhLc/aetuBcemt0bHfentV0F7bz7iDY/AFQC1h1i4G0D0wKMufuqOJFw9MOp2tSpuvCVzhCxR+Ymx/F9SaeYBAiwBawce4wu+qu3lA=
